sudo: required
dist: trusty
language: php
php: 
    - 7.1
    
before_script:
    - composer install
    - export DISPLAY=:0
    - Xvfb :0 -ac -screen 0 1280x720x16 -nolisten tcp &
    - ./vendor/laravel/dusk/bin/chromedriver-linux &
    - cp .env.testing .env
    - php artisan serve > /dev/null 2>&1 &

script:
    - ./tests/runtests.sh