sudo: required
language: php

notifications:
  email:
    on_failure: change

php:
  - 7.3

addons:
   chrome: stable

install:
  - cp .env.testing .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - ./tests/runtests.sh