sudo: required
language: php
dist: trusty

notifications:
  email:
    on_failure: change

php:
  - 7.1

install:
  - travis_retry composer install --no-interaction

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cp .env.testing .env
  - php artisan serve &

script:
  - ./tests/runtests.sh