sudo: required
dist: trusty
language: php
php: 
    - 7.1
    
before_script:
    - composer install
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - ./vendor/laravel/dusk/bin/chromedriver-linux &
    - cp .env.testing .env
    - php artisan serve > /dev/null 2>&1 &

script:
    - ./tests/runtests.sh