sudo: required
language: php
dist: trusty

notifications:
  email:
    on_failure: change

php:
  - 7.1

addons:
   chrome: stable

install:
  - cp .env.testing .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - php artisan serve &

script:
  - ./tests/runtests.sh